// Generated by dust2 (version 0.1.0) - do not edit

#include <dust2/common.hpp>

// [[dust2::class(sir)]]
// [[dust2::time_type(discrete)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(I0)]]
// [[dust2::parameter(N)]]
// [[dust2::parameter(beta)]]
// [[dust2::parameter(gamma)]]
// [[dust2::parameter(exp_noise)]]
class sir {
public:
  sir() = delete;

  using real_type = double;

  struct shared_state {
    real_type N;
    real_type I0;
    real_type beta;
    real_type gamma;
    real_type exp_noise;
  };

  using internal_state = dust2::no_internal_state;

  struct data_type {
    real_type incidence;
  };

  using rng_state_type = mcstate::random::generator<real_type>;

  static size_t size_state(const shared_state& shared) {
    return 5;
  }

  static void initial(real_type time,
                      real_type dt,
                      const shared_state& shared,
                      internal_state& internal,
                      rng_state_type& rng_state,
                      real_type * state_next) {
    state_next[0] = shared.N - shared.I0;
    state_next[1] = shared.I0;
    state_next[2] = 0;
    state_next[3] = 0;
    state_next[4] = 0;
  }

  // The main update function, converting state to state_next
  static void update(real_type time,
                     real_type dt,
                     const real_type * state,
                     const shared_state& shared,
                     internal_state& internal,
                     rng_state_type& rng_state,
                     real_type * state_next) {
    const auto S = state[0];
    const auto I = state[1];
    const auto R = state[2];
    const auto cases_cumul = state[3];
    const auto cases_inc = state[4];
    const auto p_SI = 1 - mcstate::math::exp(-shared.beta * I / shared.N * dt);
    const auto p_IR = 1 - mcstate::math::exp(-shared.gamma * dt);
    const auto n_SI = mcstate::random::binomial<real_type>(rng_state, S, p_SI);
    const auto n_IR = mcstate::random::binomial<real_type>(rng_state, I, p_IR);
    state_next[0] = S - n_SI;
    state_next[1] = I + n_SI - n_IR;
    state_next[2] = R + n_IR;
    state_next[3] = cases_cumul + n_SI;
    state_next[4] = dust2::tools::accumulate_periodic(time, static_cast<real_type>(1), cases_inc, n_SI);
  }

  static shared_state build_shared(cpp11::list pars) {
    const real_type I0 = dust2::r::read_real(pars, "I0", 10);
    const real_type N = dust2::r::read_real(pars, "N", 1000);
    const real_type beta = dust2::r::read_real(pars, "beta", 0.2);
    const real_type gamma = dust2::r::read_real(pars, "gamma", 0.1);
    const real_type exp_noise = dust2::r::read_real(pars, "exp_noise", 1e6);
    return shared_state{N, I0, beta, gamma, exp_noise};
  }

  static internal_state build_internal(const shared_state& shared) {
    return sir::internal_state{};
  }

  // This is the bit that we'll use to do fast parameter updating, and
  // we'll guarantee somewhere that the size does not change.
  static void update_shared(cpp11::list pars, shared_state& shared) {
    shared.I0 = dust2::r::read_real(pars, "I0", shared.I0);
    shared.beta = dust2::r::read_real(pars, "beta", shared.beta);
    shared.gamma = dust2::r::read_real(pars, "gamma", shared.gamma);
  }

  // This is a reasonable default implementation in the no-internal
  // case
  static void update_internal(const shared_state& shared,
                              internal_state& internal) {
  }

  static data_type build_data(cpp11::list r_data) {
    auto data = static_cast<cpp11::list>(r_data);
    auto incidence = dust2::r::read_real(data, "incidence");
    return data_type{incidence};
  }

  static real_type compare_data(const real_type time,
                                const real_type dt,
                                const real_type * state,
                                const data_type& data,
                                const shared_state& shared,
                                internal_state& internal,
                                rng_state_type& rng_state) {
    const auto incidence_observed = data.incidence;
    if (std::isnan(data.incidence)) {
      return 0;
    }
    const auto noise =
      mcstate::random::exponential(rng_state, shared.exp_noise);
    const auto incidence_modelled = state[4];
    const auto lambda = incidence_modelled + noise;
    return mcstate::density::poisson(incidence_observed, lambda, true);
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>
#include <dust2/r/discrete/filter.hpp>
#include <dust2/r/discrete/unfilter.hpp>

[[cpp11::register]]
SEXP dust2_discrete_sir_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::sexp r_dt, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic) {
  return dust2::r::dust2_discrete_alloc<sir>(r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_run_steps(cpp11::sexp ptr, cpp11::sexp r_n_steps) {
  return dust2::r::dust2_discrete_run_steps<sir>(ptr, r_n_steps);
}
[[cpp11::register]]
SEXP dust2_system_sir_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<sir>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_sir_state(cpp11::sexp ptr, bool grouped) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<sir>>(ptr, grouped);
}

[[cpp11::register]]
SEXP dust2_system_sir_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<sir>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_sir_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<sir>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_sir_set_state(cpp11::sexp ptr, cpp11::sexp r_state, bool grouped) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<sir>>(ptr, r_state, grouped);
}

[[cpp11::register]]
SEXP dust2_system_sir_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<sir>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_sir_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<sir>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_sir_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<sir>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_sir_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<sir>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_sir_update_pars(cpp11::sexp ptr, cpp11::list pars, bool grouped) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<sir>>(ptr, pars, grouped);
}

[[cpp11::register]]
SEXP dust2_system_sir_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index, bool grouped) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<sir>>(ptr, r_times, r_index, grouped);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_unfilter_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::sexp r_dt, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_index) {
  return dust2::r::dust2_discrete_unfilter_alloc<sir>(r_pars, r_time_start, r_time, r_dt, r_data, r_n_particles, r_n_groups, r_index);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_unfilter_update_pars(cpp11::sexp ptr, cpp11::list r_pars, bool grouped) {
  return dust2::r::dust2_discrete_unfilter_update_pars<sir>(ptr, r_pars, grouped);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_unfilter_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_history, bool grouped) {
  return dust2::r::dust2_discrete_unfilter_run<sir>(ptr, r_initial, save_history, grouped);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_unfilter_last_history(cpp11::sexp ptr, bool grouped) {
  return dust2::r::dust2_discrete_unfilter_last_history<sir>(ptr, grouped);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_filter_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::sexp r_dt, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_index, cpp11::sexp r_seed) {
  return dust2::r::dust2_discrete_filter_alloc<sir>(r_pars, r_time_start, r_time, r_dt, r_data, r_n_particles, r_n_groups, r_index, r_seed);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_filter_update_pars(cpp11::sexp ptr, cpp11::list r_pars, bool grouped) {
  return dust2::r::dust2_discrete_filter_update_pars<sir>(ptr, r_pars, grouped);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_filter_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_history, bool grouped) {
  return dust2::r::dust2_discrete_filter_run<sir>(ptr, r_initial, save_history, grouped);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_filter_last_history(cpp11::sexp ptr, bool grouped) {
  return dust2::r::dust2_discrete_filter_last_history<sir>(ptr, grouped);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_filter_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_discrete_filter_rng_state<sir>(ptr);
}

[[cpp11::register]]
SEXP dust2_discrete_sir_filter_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_discrete_filter_set_rng_state<sir>(ptr, r_rng_state);
}
[[cpp11::register]]
SEXP dust2_system_sir_compare_data(cpp11::sexp ptr, cpp11::sexp r_data, bool grouped) {
  return dust2::r::dust2_system_compare_data<dust2::dust_discrete<sir>>(ptr, r_data, grouped);
}
