dust_compile <- function(filename, quiet = FALSE, workdir = NULL,
                         linking_to = NULL, cpp_std = NULL,
                         compiler_options = NULL, optimisation_level = NULL) {
  # assert_file_exists(filename)
  mangle <- TRUE
  res <- generate_dust(filename, linking_to, cpp_std, optimisation_level,
                       compiler_options, mangle)

  config <- parse_metadata(filename)



  ## dust_prepare
  ## compile_and_load
}


dust_generate <- function(filename, linking_to, cpp_std, optimisation_level,
                          compiler_options, mangle) {
  config <- parse_metadata(filename)
  if (grepl("^[A-Za-z][A-Zxa-z0-9]*$", config$name)) {
    base <- config$name
  } else {
    base <- "dust"
  }
  if (mangle) {
    base <- paste0(base, hash_file(filename))
  }
  model <- read_lines(filename)

  data <- dust_template_data(model, config, linking_to, cpp_std,
                             optimisation_level, compiler_options)
  data$path_dust_include <- dust_file("include")
  data$system_requirements <- data$cpp_std %||% "R (>= 4.0.0)"

  ret <- list(
    description = substitute_dust_template(data, "DESCRIPTION"),
    namespace = substitute_dust_template(data, "NAMESPACE"),
    makevars = substitute_dust_template(data, "Makevars"),
    r = substitute_dust_template(data, "dust.R"),
    cpp = generate_cpp(data))
}


generate_cpp <- function(model, data) {
  includes <- c("cpp11.hpp", "dust2/r/cpu.hpp")
  code <- substitute_dust_template(data, "dust_core.cpp")

  header <- sprintf(
    "// Generated by dust2 (version %s) - do not edit",
    data$dust_version)

  if (config$has_compare) {
    includes <- c(includes, "dust2/r/filter.hpp")
    code <- c(code,
              "",
              substitute_dust_template(data, "dust_compare.cpp"))
  }

  c(header,
    "",
    model,
    "",
    includes,
    ""
    code)
}


dust_template_data <- function(model, config, linking_to, cpp_std,
                               optimisation_level, compiler_options) {

  if (!is.null(linking_to)) {
    assert_is(linking_to, "character")
  }
  linking_to <- paste(union("cpp11", linking_to), collapse = ", ")
  cpp_std <- validate_cpp_std(cpp_std)
  compiler_options <- build_compiler_options(compiler_options,
                                             optimisation_level)
  list(name = config$name,
       class = config$class,
       package = config$name,
       linking_to = linking_to,
       cpp_std = cpp_std,
       compiler_options = compiler_options)
}


build_compiler_options <- function(compiler_options, optimisation_level) {
  if (!is.null(optimisation_level)) {
    opts <- switch(
      optimisation_level,
      none = "-O0",
      standard = "-O2",
      max = c("-O3", "-ffast-math"),
      cli::cli_abort(
        "Unknown 'optimisation_level' value '{optimisation_level}'"))
    compiler_options <- c(compiler_options, opts)
  }
  paste(compiler_options, collapse = " ")
}


substitute_dust_template <- function(data, src) {
  template <- read_lines(dust_file(file.path("template", src)))
  glue_whisker(template, data)
}
