# Generated by cpp11: do not edit by hand

dust2_system_logistic_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_logistic_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_logistic_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_dust2_dust2_system_logistic_internals`, ptr, include_coefficients, include_history)
}

dust2_system_logistic_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_logistic_run_to_time`, ptr, r_time)
}

dust2_system_logistic_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_logistic_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_logistic_time <- function(ptr) {
  .Call(`_dust2_dust2_system_logistic_time`, ptr)
}

dust2_system_logistic_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_logistic_set_state_initial`, ptr)
}

dust2_system_logistic_set_state <- function(ptr, r_state) {
  .Call(`_dust2_dust2_system_logistic_set_state`, ptr, r_state)
}

dust2_system_logistic_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_logistic_reorder`, ptr, r_index)
}

dust2_system_logistic_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_logistic_rng_state`, ptr)
}

dust2_system_logistic_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_logistic_set_rng_state`, ptr, r_rng_state)
}

dust2_system_logistic_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_logistic_set_time`, ptr, r_time)
}

dust2_system_logistic_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_logistic_update_pars`, ptr, pars)
}

dust2_system_logistic_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_logistic_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_malaria_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_malaria_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_malaria_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_dust2_dust2_system_malaria_internals`, ptr, include_coefficients, include_history)
}

dust2_system_malaria_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_malaria_run_to_time`, ptr, r_time)
}

dust2_system_malaria_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_malaria_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_malaria_time <- function(ptr) {
  .Call(`_dust2_dust2_system_malaria_time`, ptr)
}

dust2_system_malaria_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_malaria_set_state_initial`, ptr)
}

dust2_system_malaria_set_state <- function(ptr, r_state) {
  .Call(`_dust2_dust2_system_malaria_set_state`, ptr, r_state)
}

dust2_system_malaria_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_malaria_reorder`, ptr, r_index)
}

dust2_system_malaria_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_malaria_rng_state`, ptr)
}

dust2_system_malaria_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_malaria_set_rng_state`, ptr, r_rng_state)
}

dust2_system_malaria_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_malaria_set_time`, ptr, r_time)
}

dust2_system_malaria_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_malaria_update_pars`, ptr, pars)
}

dust2_system_malaria_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_malaria_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_malaria_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads) {
  .Call(`_dust2_dust2_unfilter_malaria_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads)
}

dust2_filter_malaria_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed) {
  .Call(`_dust2_dust2_filter_malaria_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed)
}

dust2_system_malaria_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_malaria_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_malaria_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_dust2_dust2_unfilter_malaria_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_malaria_run <- function(ptr, r_initial, save_history, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_malaria_run`, ptr, r_initial, save_history, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_malaria_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_malaria_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_malaria_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_malaria_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_malaria_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_dust2_dust2_filter_malaria_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_malaria_run <- function(ptr, r_initial, save_history, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_malaria_run`, ptr, r_initial, save_history, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_malaria_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_malaria_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_malaria_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_malaria_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_malaria_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_filter_malaria_rng_state`, ptr)
}

dust2_filter_malaria_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_filter_malaria_set_rng_state`, ptr, r_rng_state)
}

cpp_openmp_info <- function() {
  .Call(`_dust2_cpp_openmp_info`)
}

dust2_system_sir_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_sir_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_sir_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_sir_run_to_time`, ptr, r_time)
}

dust2_system_sir_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sir_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sir_time <- function(ptr) {
  .Call(`_dust2_dust2_system_sir_time`, ptr)
}

dust2_system_sir_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_sir_set_state_initial`, ptr)
}

dust2_system_sir_set_state <- function(ptr, r_state) {
  .Call(`_dust2_dust2_system_sir_set_state`, ptr, r_state)
}

dust2_system_sir_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_sir_reorder`, ptr, r_index)
}

dust2_system_sir_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_sir_rng_state`, ptr)
}

dust2_system_sir_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_sir_set_rng_state`, ptr, r_rng_state)
}

dust2_system_sir_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_sir_set_time`, ptr, r_time)
}

dust2_system_sir_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_sir_update_pars`, ptr, pars)
}

dust2_system_sir_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sir_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads) {
  .Call(`_dust2_dust2_unfilter_sir_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads)
}

dust2_filter_sir_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed) {
  .Call(`_dust2_dust2_filter_sir_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed)
}

dust2_system_sir_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sir_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_dust2_dust2_unfilter_sir_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_sir_run <- function(ptr, r_initial, save_history, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sir_run`, ptr, r_initial, save_history, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sir_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sir_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_dust2_dust2_filter_sir_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_sir_run <- function(ptr, r_initial, save_history, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_sir_run`, ptr, r_initial, save_history, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_sir_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_sir_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_filter_sir_rng_state`, ptr)
}

dust2_filter_sir_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_filter_sir_set_rng_state`, ptr, r_rng_state)
}

dust2_unfilter_sir_last_gradient <- function(ptr, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sir_last_gradient`, ptr, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sirode_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_sirode_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_sirode_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_dust2_dust2_system_sirode_internals`, ptr, include_coefficients, include_history)
}

dust2_system_sirode_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_sirode_run_to_time`, ptr, r_time)
}

dust2_system_sirode_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sirode_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sirode_time <- function(ptr) {
  .Call(`_dust2_dust2_system_sirode_time`, ptr)
}

dust2_system_sirode_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_sirode_set_state_initial`, ptr)
}

dust2_system_sirode_set_state <- function(ptr, r_state) {
  .Call(`_dust2_dust2_system_sirode_set_state`, ptr, r_state)
}

dust2_system_sirode_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_sirode_reorder`, ptr, r_index)
}

dust2_system_sirode_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_sirode_rng_state`, ptr)
}

dust2_system_sirode_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_sirode_set_rng_state`, ptr, r_rng_state)
}

dust2_system_sirode_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_sirode_set_time`, ptr, r_time)
}

dust2_system_sirode_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_sirode_update_pars`, ptr, pars)
}

dust2_system_sirode_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sirode_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sirode_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads) {
  .Call(`_dust2_dust2_unfilter_sirode_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads)
}

dust2_filter_sirode_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed) {
  .Call(`_dust2_dust2_filter_sirode_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed)
}

dust2_system_sirode_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sirode_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sirode_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_dust2_dust2_unfilter_sirode_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_sirode_run <- function(ptr, r_initial, save_history, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sirode_run`, ptr, r_initial, save_history, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sirode_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sirode_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sirode_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sirode_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sirode_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_dust2_dust2_filter_sirode_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_sirode_run <- function(ptr, r_initial, save_history, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_sirode_run`, ptr, r_initial, save_history, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sirode_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_sirode_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sirode_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_sirode_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sirode_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_filter_sirode_rng_state`, ptr)
}

dust2_filter_sirode_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_filter_sirode_set_rng_state`, ptr, r_rng_state)
}

test_resample_weight <- function(w, u) {
  .Call(`_dust2_test_resample_weight`, w, u)
}

test_scale_log_weights <- function(w) {
  .Call(`_dust2_test_scale_log_weights`, w)
}

test_trajectories_ <- function(r_time, r_state, r_order, r_index_state, r_index_group, r_select_particle, reorder) {
  .Call(`_dust2_test_trajectories_`, r_time, r_state, r_order, r_index_state, r_index_group, r_select_particle, reorder)
}

test_check_dimensions <- function(value, r_dim, name) {
  .Call(`_dust2_test_check_dimensions`, value, r_dim, name)
}

test_read_dimensions <- function(value, rank, name) {
  .Call(`_dust2_test_read_dimensions`, value, rank, name)
}

test_interpolate_search <- function(target, x) {
  .Call(`_dust2_test_interpolate_search`, target, x)
}

test_interpolate_constant1 <- function(t, y, z) {
  .Call(`_dust2_test_interpolate_constant1`, t, y, z)
}

test_interpolate_linear1 <- function(t, y, z) {
  .Call(`_dust2_test_interpolate_linear1`, t, y, z)
}

test_interpolate_spline1 <- function(t, y, z) {
  .Call(`_dust2_test_interpolate_spline1`, t, y, z)
}

test_interpolate_constant2 <- function(t, r_y, z) {
  .Call(`_dust2_test_interpolate_constant2`, t, r_y, z)
}

test_interpolate_linear2 <- function(t, r_y, z) {
  .Call(`_dust2_test_interpolate_linear2`, t, r_y, z)
}

test_interpolate_spline2 <- function(t, r_y, z) {
  .Call(`_dust2_test_interpolate_spline2`, t, r_y, z)
}

test_sum <- function(r_x, r_m) {
  .Call(`_dust2_test_sum`, r_x, r_m)
}

test_min <- function(r_x, r_m) {
  .Call(`_dust2_test_min`, r_x, r_m)
}

dust2_system_walk_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_walk_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_walk_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_walk_run_to_time`, ptr, r_time)
}

dust2_system_walk_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_walk_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_walk_time <- function(ptr) {
  .Call(`_dust2_dust2_system_walk_time`, ptr)
}

dust2_system_walk_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_walk_set_state_initial`, ptr)
}

dust2_system_walk_set_state <- function(ptr, r_state) {
  .Call(`_dust2_dust2_system_walk_set_state`, ptr, r_state)
}

dust2_system_walk_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_walk_reorder`, ptr, r_index)
}

dust2_system_walk_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_walk_rng_state`, ptr)
}

dust2_system_walk_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_walk_set_rng_state`, ptr, r_rng_state)
}

dust2_system_walk_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_walk_set_time`, ptr, r_time)
}

dust2_system_walk_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_walk_update_pars`, ptr, pars)
}

dust2_system_walk_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_walk_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}
