# Generated by cpp11: do not edit by hand

dust2_cpu_sir_alloc <- function(r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic) {
  .Call(`_dust2_dust2_cpu_sir_alloc`, r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic)
}

dust2_cpu_sir_run_steps <- function(ptr, r_n_steps) {
  .Call(`_dust2_dust2_cpu_sir_run_steps`, ptr, r_n_steps)
}

dust2_cpu_sir_state <- function(ptr, grouped) {
  .Call(`_dust2_dust2_cpu_sir_state`, ptr, grouped)
}

dust2_cpu_sir_time <- function(ptr) {
  .Call(`_dust2_dust2_cpu_sir_time`, ptr)
}

dust2_cpu_sir_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_cpu_sir_set_state_initial`, ptr)
}

dust2_cpu_sir_set_state <- function(ptr, r_state, grouped) {
  .Call(`_dust2_dust2_cpu_sir_set_state`, ptr, r_state, grouped)
}

dust2_cpu_sir_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_cpu_sir_rng_state`, ptr)
}

dust2_cpu_sir_compare_data <- function(ptr, r_data, grouped) {
  .Call(`_dust2_dust2_cpu_sir_compare_data`, ptr, r_data, grouped)
}

dust2_cpu_walk_alloc <- function(r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic) {
  .Call(`_dust2_dust2_cpu_walk_alloc`, r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic)
}

dust2_cpu_walk_run_steps <- function(ptr, r_n_steps) {
  .Call(`_dust2_dust2_cpu_walk_run_steps`, ptr, r_n_steps)
}

dust2_cpu_walk_state <- function(ptr, grouped) {
  .Call(`_dust2_dust2_cpu_walk_state`, ptr, grouped)
}

dust2_cpu_walk_time <- function(ptr) {
  .Call(`_dust2_dust2_cpu_walk_time`, ptr)
}

dust2_cpu_walk_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_cpu_walk_set_state_initial`, ptr)
}

dust2_cpu_walk_set_state <- function(ptr, r_state, grouped) {
  .Call(`_dust2_dust2_cpu_walk_set_state`, ptr, r_state, grouped)
}

dust2_cpu_walk_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_cpu_walk_reorder`, ptr, r_index)
}

dust2_cpu_walk_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_cpu_walk_rng_state`, ptr)
}

dust2_cpu_walk_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_cpu_walk_set_time`, ptr, r_time)
}

dust2_cpu_walk_update_pars <- function(ptr, pars, grouped) {
  .Call(`_dust2_dust2_cpu_walk_update_pars`, ptr, pars, grouped)
}
