# Generated by cpp11: do not edit by hand

dust2_system_logistic_alloc <- function(r_pars, r_time, r_ode_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_logistic_alloc`, r_pars, r_time, r_ode_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_logistic_internals <- function(ptr, include_coefficients) {
  .Call(`_dust2_dust2_system_logistic_internals`, ptr, include_coefficients)
}

dust2_system_logistic_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_logistic_run_to_time`, ptr, r_time)
}

dust2_system_logistic_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_logistic_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_logistic_time <- function(ptr) {
  .Call(`_dust2_dust2_system_logistic_time`, ptr)
}

dust2_system_logistic_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_logistic_set_state_initial`, ptr)
}

dust2_system_logistic_set_state <- function(ptr, r_state, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_logistic_set_state`, ptr, r_state, preserve_group_dimension)
}

dust2_system_logistic_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_logistic_reorder`, ptr, r_index)
}

dust2_system_logistic_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_logistic_rng_state`, ptr)
}

dust2_system_logistic_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_logistic_set_rng_state`, ptr, r_rng_state)
}

dust2_system_logistic_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_logistic_set_time`, ptr, r_time)
}

dust2_system_logistic_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_logistic_update_pars`, ptr, pars)
}

dust2_system_logistic_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_logistic_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sir_alloc <- function(r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_sir_alloc`, r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_sir_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_sir_run_to_time`, ptr, r_time)
}

dust2_system_sir_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sir_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sir_time <- function(ptr) {
  .Call(`_dust2_dust2_system_sir_time`, ptr)
}

dust2_system_sir_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_sir_set_state_initial`, ptr)
}

dust2_system_sir_set_state <- function(ptr, r_state, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sir_set_state`, ptr, r_state, preserve_group_dimension)
}

dust2_system_sir_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_sir_reorder`, ptr, r_index)
}

dust2_system_sir_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_sir_rng_state`, ptr)
}

dust2_system_sir_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_sir_set_rng_state`, ptr, r_rng_state)
}

dust2_system_sir_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_sir_set_time`, ptr, r_time)
}

dust2_system_sir_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_sir_update_pars`, ptr, pars)
}

dust2_system_sir_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sir_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_alloc <- function(r_pars, r_time_start, r_time, r_dt, r_data, r_n_particles, r_n_groups, r_n_threads, r_index_state) {
  .Call(`_dust2_dust2_unfilter_sir_alloc`, r_pars, r_time_start, r_time, r_dt, r_data, r_n_particles, r_n_groups, r_n_threads, r_index_state)
}

dust2_filter_sir_alloc <- function(r_pars, r_time_start, r_time, r_dt, r_data, r_n_particles, r_n_groups, r_n_threads, r_index_state, r_seed) {
  .Call(`_dust2_dust2_filter_sir_alloc`, r_pars, r_time_start, r_time, r_dt, r_data, r_n_particles, r_n_groups, r_n_threads, r_index_state, r_seed)
}

dust2_system_sir_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sir_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_dust2_dust2_unfilter_sir_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_sir_run <- function(ptr, r_initial, save_history, adjoint, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sir_run`, ptr, r_initial, save_history, adjoint, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_last_history <- function(ptr, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sir_last_history`, ptr, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_dust2_dust2_filter_sir_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_sir_run <- function(ptr, r_initial, save_history, index_group, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_sir_run`, ptr, r_initial, save_history, index_group, preserve_group_dimension)
}

dust2_filter_sir_last_history <- function(ptr, r_index_group, select_random_particle, preserve_group_dimension) {
  .Call(`_dust2_dust2_filter_sir_last_history`, ptr, r_index_group, select_random_particle, preserve_group_dimension)
}

dust2_filter_sir_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_filter_sir_rng_state`, ptr)
}

dust2_filter_sir_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_filter_sir_set_rng_state`, ptr, r_rng_state)
}

dust2_unfilter_sir_last_gradient <- function(ptr, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_unfilter_sir_last_gradient`, ptr, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sirode_alloc <- function(r_pars, r_time, r_ode_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_sirode_alloc`, r_pars, r_time, r_ode_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_sirode_internals <- function(ptr, include_coefficients) {
  .Call(`_dust2_dust2_system_sirode_internals`, ptr, include_coefficients)
}

dust2_system_sirode_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_sirode_run_to_time`, ptr, r_time)
}

dust2_system_sirode_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sirode_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sirode_time <- function(ptr) {
  .Call(`_dust2_dust2_system_sirode_time`, ptr)
}

dust2_system_sirode_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_sirode_set_state_initial`, ptr)
}

dust2_system_sirode_set_state <- function(ptr, r_state, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sirode_set_state`, ptr, r_state, preserve_group_dimension)
}

dust2_system_sirode_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_sirode_reorder`, ptr, r_index)
}

dust2_system_sirode_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_sirode_rng_state`, ptr)
}

dust2_system_sirode_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_sirode_set_rng_state`, ptr, r_rng_state)
}

dust2_system_sirode_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_sirode_set_time`, ptr, r_time)
}

dust2_system_sirode_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_sirode_update_pars`, ptr, pars)
}

dust2_system_sirode_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_sirode_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

test_resample_weight <- function(w, u) {
  .Call(`_dust2_test_resample_weight`, w, u)
}

test_scale_log_weights <- function(w) {
  .Call(`_dust2_test_scale_log_weights`, w)
}

test_history_ <- function(r_time, r_state, r_order, r_index_group, r_index_particle, reorder) {
  .Call(`_dust2_test_history_`, r_time, r_state, r_order, r_index_group, r_index_particle, reorder)
}

test_interpolate_search <- function(target, x) {
  .Call(`_dust2_test_interpolate_search`, target, x)
}

test_interpolate_constant1 <- function(t, y, z) {
  .Call(`_dust2_test_interpolate_constant1`, t, y, z)
}

test_interpolate_linear1 <- function(t, y, z) {
  .Call(`_dust2_test_interpolate_linear1`, t, y, z)
}

test_interpolate_spline1 <- function(t, y, z) {
  .Call(`_dust2_test_interpolate_spline1`, t, y, z)
}

dust2_system_walk_alloc <- function(r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_dust2_dust2_system_walk_alloc`, r_pars, r_time, r_dt, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_walk_run_to_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_walk_run_to_time`, ptr, r_time)
}

dust2_system_walk_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_walk_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_walk_time <- function(ptr) {
  .Call(`_dust2_dust2_system_walk_time`, ptr)
}

dust2_system_walk_set_state_initial <- function(ptr) {
  .Call(`_dust2_dust2_system_walk_set_state_initial`, ptr)
}

dust2_system_walk_set_state <- function(ptr, r_state, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_walk_set_state`, ptr, r_state, preserve_group_dimension)
}

dust2_system_walk_reorder <- function(ptr, r_index) {
  .Call(`_dust2_dust2_system_walk_reorder`, ptr, r_index)
}

dust2_system_walk_rng_state <- function(ptr) {
  .Call(`_dust2_dust2_system_walk_rng_state`, ptr)
}

dust2_system_walk_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_dust2_dust2_system_walk_set_rng_state`, ptr, r_rng_state)
}

dust2_system_walk_set_time <- function(ptr, r_time) {
  .Call(`_dust2_dust2_system_walk_set_time`, ptr, r_time)
}

dust2_system_walk_update_pars <- function(ptr, pars) {
  .Call(`_dust2_dust2_system_walk_update_pars`, ptr, pars)
}

dust2_system_walk_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_dust2_dust2_system_walk_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}
