## Generated by dust2 (version 0.2.0) - do not edit
logistic <- structure(
  function() get("logistic"),
  class = "dust_system_generator",
  name = "logistic",
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
malaria <- structure(
  function() get("malaria"),
  class = "dust_system_generator",
  name = "malaria",
  properties = list(
    time_type = "mixed",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = NULL)
sir <- structure(
  function() get("sir"),
  class = "dust_system_generator",
  name = "sir",
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = TRUE),
  default_dt = 1)
sirode <- structure(
  function() get("sirode"),
  class = "dust_system_generator",
  name = "sirode",
  properties = list(
    time_type = "continuous",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = NULL)
walk <- structure(
  function() get("walk"),
  class = "dust_system_generator",
  name = "walk",
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
