## Generated by dust2 (version 0.1.0) - do not edit
logistic <- function() {
  dust_system_generator("logistic", "continuous")
}
sir <- function() {
  dust_system_generator("sir", "discrete")
}
walk <- function() {
  dust_system_generator("walk", "discrete")
}
